import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "맛집코스를 만들어보자",
  description: "Generated by 맛집코스",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" />
      </head>
      <body className={inter.className}>
        <nav class="navbar">
          <input placeholder="Search" class="nav-search" />
          <div class="search-button">
            <i class="fas fa-search" style={{color: "#ffffff"}}></i>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
